# --- CONSTANTES DE ESTILO (TAMAÑO GRANDE) ---
FONT_NORMAL = ("Segoe UI", 16)
FONT_BOLD = ("Segoe UI", 16, "bold")
FONT_TITLE = ("Segoe UI", 32, "bold")
FONT_MENU_TITLE = ("Segoe UI", 22, "bold")

APP_BG_COLOR = "#E7EEF4"
FRAME_BG_COLOR = "#FFFFFF"
ENTRY_BG_COLOR = "#FFFFFF"
BUTTON_SECONDARY_COLOR = "#8EC1F2"
BUTTON_SECONDARY_HOVER = "#AAC4DA"
ACCENT_PURPLE = "#AAC4DA"
ACCENT_PINK = "#AAC4DA"
TEXT_COLOR = "#000"
BUTTON_SKY_BLUE_COLOR = "#AAC4DA"
BUTTON_SKY_BLUE_HOVER = "#96CBF6"
BORDER_COLOR_SKY_BLUE = "#AAC4DA"
